### PR TITLE
Correct inplace for complex BLAS and fix some accumulation against nondifferentails

### LINKED ISSUE #278: Inplace Accumulation for complex BLAS wrong?
Looking at the Integration CI failures on  https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/59
it seems like we might actually have some rules that are incorrect for inplace accumulation, if the inputs are Complex

### PR DESCRIPTION
**Pull request by oxinabox**
closes #278 

This PR is the follow up from the integration tests failing in
https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/59

The core problem with the complex numbers was we were doing
`a = (b + a)' ` 
but we should have been doing
`a = b' + a`
but BLAS doesn;t have a shorthand for that
so what we actually do is:
`a = (b + a')'`

Other problem was us using some things were not differentials, and trying to acculate against them.

Requires
https://github.com/JuliaDiff/FiniteDifferences.jl/pull/111
for tests to pass, as needs to `to_vec` support for `AbstractZeros`
because its used in how ChainRulesTestUtil checks equality for `Composites`
which doesn't seem great, and seems like  in longer term to destructure the eqaulity checks is better
like in https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/57

### CODE REVIEW

File: test/rulesets/packages/SpecialFunctions.jl [hunk 1]
```diff
@@ -50,7 +50,7 @@ end
             isreal(x) || continue
 
             Δx, x̄ = randn(2)
-            Δz = (randn(), randn())
+            Δz = Composite{Tuple{Float64, DoesNotExist}}(randn(), Zero())
```
Comment (sethaxen) [inline test/rulesets/packages/SpecialFunctions.jl:53]: Why this change? Is it related to the BLAS fixes?

File: test/rulesets/Base/evalpoly.jl [hunk 2]
```diff
@@ -22,14 +22,14 @@
             sp = (np..., np...)
             x, ẋ, x̄ = randn(T, sx...), randn(T, sx...), randn(T, sx...)
             p = [randn(T, sp...) for _ in 1:m]
+            @show p
```
Comment (sethaxen) [inline test/rulesets/Base/evalpoly.jl:25]: Did you mean to make this change?

File: test/rulesets/Base/evalpoly.jl [hunk 3]
```diff
@@ -22,14 +22,14 @@
...
             ṗ = [randn(T, sp...) for _ in 1:m]
             p̄ = [randn(T, sp...) for _ in 1:m]
             Ω = evalpoly(x, p)
             Ω̄ = randn(T, size(Ω)...)
             frule_test(evalpoly, (x, ẋ), (p, ṗ))
-            frule_test(evalpoly, (x, ẋ), (Tuple(p), Tuple(ṗ)))
+            frule_test(evalpoly, (x, ẋ), (Tuple(p), rand_tangent(Tuple(p))))
```
Comment (sethaxen) [inline test/rulesets/Base/evalpoly.jl:31]: Would it make sense to use `rand_tangent` for all tangents in this test set?

File: test/rulesets/Base/base.jl [hunk 4]
```diff
@@ -126,14 +126,14 @@
         frule_test(identity, (randn(T, 4), randn(T, 4)))
         frule_test(
             identity,
-            (Composite{Tuple}(randn(T, 3)...), Composite{Tuple}(randn(T, 3)...))
+            (Tuple(randn(T, 3)), Composite{Tuple{T, T, T}}(randn(T, 3)...))
```
Comment (sethaxen) [inline test/rulesets/Base/base.jl:129]: Could you use `rand_tangent` here as well?

File: test/rulesets/Base/base.jl [hunk 5]
```diff
@@ -126,14 +126,14 @@
...
         )
 
         rrule_test(identity, randn(T), (randn(T), randn(T)))
         rrule_test(identity, randn(T, 4), (randn(T, 4), randn(T, 4)))
         rrule_test(
-            identity, Tuple(randn(T, 3)),
-            (Composite{Tuple}(randn(T, 3)...), Composite{Tuple}(randn(T, 3)...))
+            identity, Composite{Tuple{T, T, T}}(randn(T, 3)...),
```
Comment (sethaxen) [inline test/rulesets/Base/base.jl:135]: Could you use `rand_tangent` here as well?

**Review by sethaxen — APPROVED** [review]
The BLAS fixes LGTM. I had a few minor questions about the changes to the tests.

Also, I wonder if it would make sense to also include in this PR some fixes to not allocate new conjugated matrices in the BLAS rules? e.g. in
https://github.com/JuliaDiff/ChainRules.jl/blob/c877550430a3cb0f657f43ccbf4e64b13b7177a7/src/rulesets/LinearAlgebra/blas.jl#L134-L137,
we allocate a new matrix `A`, which I think can be made faster by allocating a new vector instead and then conjugating a vector in-place:
```julia
             ∂x = InplaceableThunk( 
                 @thunk(gemv('N', α', conj(A), ȳ)), 
                 x̄ -> conj!(gemv!('N', α, A, conj(ȳ), one(T), conj!(x̄)))
             ) 
```

File: test/rulesets/Base/evalpoly.jl (hunk 2 above)
Comment (oxinabox) [reply test/rulesets/Base/evalpoly.jl:25]: I did not`

File: test/rulesets/packages/SpecialFunctions.jl (hunk 1 above)
Comment (oxinabox) [reply test/rulesets/packages/SpecialFunctions.jl:53]: Not related to the problem with BLAS, but it does cause a problem for testing accumulation.
Since you can add to a tuple

File: test/rulesets/Base/evalpoly.jl (hunk 2 above)
Comment (oxinabox) [reply test/rulesets/Base/evalpoly.jl:25]:
```suggestion
```

File: test/rulesets/Base/evalpoly.jl (hunk 3 above)
Comment (oxinabox) [reply test/rulesets/Base/evalpoly.jl:30]: It would make sense to use `rand_tangent` in a whole ton of places.
Infact, we should use it by default everywhere.
See: https://github.com/JuliaDiff/ChainRulesTestUtils.jl/issues/67

I am not inclines to get through and change to using it manually in a bunch of places when what we should do is change to using it automatically everywhere.

I made the change here as it was shorted than expressly writing out the Composite
I could make it in more places here, but that would be longer than what we have.
so I figure the rest could wait for us to do tangent generation automatically

**Comment by oxinabox** [comment]
> Also, I wonder if it would make sense to also include in this PR some fixes to not allocate new conjugated matrices in the BLAS rules? 

That is a good idea.
It would be worth benchmarking it.
I think not in this PR though, as this is a bug-fix, and better to get it in sooner, and have other PR for a feature enhancement.
I will open an issue.

File: test/rulesets/Base/evalpoly.jl (hunk 3 above)
Comment (sethaxen) [reply test/rulesets/Base/evalpoly.jl:30]: Okay, makes sense

File: test/rulesets/Base/fastmath_able.jl [hunk 6]
```diff
@@ -52,7 +54,7 @@ const FASTABLE_AST = quote
         @testset "Inverses" for x = (0.5, Complex(0.5, 0.25))
             test_scalar(asin, x)
             test_scalar(acos, x)
-            test_scalar(atan, x)
+            test_scalar(atan, x; )
```
Comment (oxinabox) [inline test/rulesets/Base/fastmath_able.jl:57]:
```suggestion
            test_scalar(atan, x)
```

**Comment by oxinabox** [comment]
This passes, once we have
https://github.com/JuliaDiff/ChainRules.jl/pull/286
to use FiniteDifferences v0.11

File: test/rulesets/Base/fastmath_able.jl [hunk 7]
```diff
@@ -164,17 +167,17 @@ const FASTABLE_AST = quote
 
         @testset "^(x::$T, n::$T)" for T in (Float64, ComplexF64)
             # for real x and n, x must be >0
-            x = T <: Real ? 15rand() : 15randn(ComplexF64)
-            Δx, x̄ = 10rand(T, 2)
-            y, Δy, ȳ = rand(T, 3)
+            x, Δx, x̄ = rand(T, 2) .+ 3
+            y, Δy, ȳ = rand(T, 2) .+ 3
```
Comment (oxinabox) [inline test/rulesets/Base/fastmath_able.jl:171]:
```suggestion
            x, Δx, x̄ = rand(T, 3) .+ 3
            y, Δy, ȳ = rand(T, 3) .+ 3
```
