### PR TITLE
Fix Composite of SVD

### LINKED ISSUE #106: Define `rrule` for SVD.Vt
we have `U`, `S`, `V`, but not `Vt` https://github.com/JuliaDiff/ChainRules.jl/blob/d8339cc1ecd8b8180dfb4f6797b168d287b5e92c/src/rulesets/LinearAlgebra/factorization.jl#L23

### LINKED ISSUE #389: Canonicalize Composite{SVD}
Making an issue out of https://github.com/JuliaDiff/ChainRules.jl/pull/388
```julia
julia> using ChainRules

julia> using LinearAlgebra

julia> x = rand(3, 2);

julia> F = svd(x);

julia> y, pb = rrule(getproperty, F, :V);

julia> c = pb(rand(3, 2))[2]
Composite{SVD{Float64,Float64,Array{Float64,2}}}(V = [0.17383499380772904 0.39005912263976916; 0.45401136256238694 0.857760693263997; 0.5536276381177541 0.3029145326674041],)

julia> canonicalize(c)
ERROR: ArgumentError: Composite fields do not match primal fields.
Composite fields: (:V,). Primal (SVD{Float64,Float64,Array{Float64,2}}) fields: (:U, :S, :Vt)
```

Will do what Seth said https://github.com/JuliaDiff/ChainRules.jl/pull/388#issuecomment-805223728

### PR DESCRIPTION
**Pull request by mzgubic**
Closes #389 , closes #106

### CODE REVIEW

File: test/rulesets/LinearAlgebra/factorization.jl [hunk 1]
```diff
@@ -140,7 +136,7 @@ end
             end
             @test X̄.U ≈ ones(3, 2) atol=1e-6
             @test X̄.S ≈ ones(2) atol=1e-6
-            @test X̄.V ≈ ones(2, 2) atol=1e-6
+            @test X̄.Vt ≈ 2 * ones(2, 2) atol=1e-6 # * 2 because V and Vt both accumulate to Vt
```
Comment (sethaxen) [inline test/rulesets/LinearAlgebra/factorization.jl:139]: Could you move these tests into the loop to avoid this collision of two cotangents?

File: test/rulesets/LinearAlgebra/factorization.jl [hunk 2]
```diff
@@ -130,7 +126,7 @@ end
             X = [1.0 2.0; 3.0 4.0; 5.0 6.0]
             F, dX_pullback = rrule(svd, X)
             X̄ = Composite{typeof(F)}(U=zeros(3, 2), S=zeros(2), V=zeros(2, 2))
-            for p in [:U, :S, :V]
+            for p in [:U, :S, :V, :Vt]
                 Y, dF_pullback = rrule(getproperty, F, p)
                 Ȳ = ones(size(Y)...)
```
Comment (sethaxen) [inline test/rulesets/LinearAlgebra/factorization.jl:131]: I know it's not part of this PR, but it would be safer to have a random cotangent here.

**Review by sethaxen — APPROVED** [review]
LGTM! Just minor comments. Feel free to merge when ready.

File: test/rulesets/LinearAlgebra/factorization.jl (hunk 1 above)
Comment (mzgubic) [reply test/rulesets/LinearAlgebra/factorization.jl:139]: Then we end up with something like
`@test getproperty(dF, p) == ones(size(getproperty(X̄, p)))`
because we have to take care of the sizes. And that's probably less clear?

File: test/rulesets/LinearAlgebra/factorization.jl (hunk 2 above)
Comment (sethaxen) [reply test/rulesets/LinearAlgebra/factorization.jl:131]: Sure that's fine.

Comment (mzgubic) [reply test/rulesets/LinearAlgebra/factorization.jl:131]: Actually, testing with `test_rrule` shows up problems:
```julia
ERROR: MethodError: no method matching adjoint(::Composite{Adjoint{Float64,Array{Float64,2}},NamedTuple{(:parent,),Tuple{Array{Float64,2}}}})
Closest candidates are:
  adjoint(::Missing) at missing.jl:100
  adjoint(::Number) at number.jl:169
  adjoint(::Adjoint) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/adjtrans.jl:164
  ...
Stacktrace:
 [1] top-level scope at REPL[32]:1
```
for the
```julia
       elseif x === :V
             C(Vt=Ȳ',)
```
part. See https://github.com/JuliaDiff/ChainRulesCore.jl/issues/312, do you have an opinion on that?

**Comment by mzgubic** [comment]
I've modernised the tests from the manual finite differences tests to the new `test_rrule` interface. Would you like to take another look?

**Comment by mzgubic** [comment]
oh damn the tests fail with the new version of ChainRulesCore :grimace

**Review by sethaxen — APPROVED** [review]
LGTM. It's nice that it uses `test_rrule` now as well. Feel free to merge if all non-nightly tests pass.
