### PR TITLE
Fix exp rules for some matrices

### LINKED ISSUE #595: `frule` for `LinearAlgebra.exp!` often gives wrong result
On Julia 1.7.0 with ChainRules v1.27.0 and FiniteDifferences v0.12.24 I noticed the following when comparing a manually computed Jacobian using ChainRules to one computed using FiniteDifferences.

```julia
julia> using ChainRulesCore, ChainRules, FiniteDifferences, LinearAlgebra, Random

julia> function compare(A)
           ΔA = ((tmp = zeros(3, 3); tmp[i] = 1; tmp) for i = 1:9)
           Ȧ = reduce(hcat, (vec(ChainRulesCore.frule((NoTangent(), ΔA), LinearAlgebra.exp!, copy(A))[2]) for ΔA in ΔA))
           dA = jacobian(central_fdm(12, 1), LinearAlgebra.exp!, copy(A))[1] # Similar results if I use exp here
           norm(dA - Ȧ) / norm(dA)
       end

julia> Random.seed!(4); A = randn(3, 3)
3×3 Matrix{Float64}:
 -1.43958    0.723766  0.804293
  0.401951  -1.78305   0.471269
  0.748248  -0.853744  0.788465

julia> compare(A)
2.236952800467401e-11 # Good

julia> Random.seed!(5); A = randn(3, 3)
3×3 Matrix{Float64}:
 0.378172   0.59316   -0.650402
 0.949351  -0.553783   0.00584074
 2.48586    0.858478  -0.54068

julia> compare(A)
1.3838115170508762 # Bad
```

In case this info helps, I tried 1000 different random seeds, and 773 of them failed with relative error >= 1e-8 (749 of them failed with relative error >= 0.01). In 323 of the failure cases the primal input was modified in the `frule` (all for cases with relative error >= 0.01), whereas the primal input was modified in just 2 of the successful cases.

Am I doing something wrong? I noticed in #353 commentary about FiniteDifferences hitting multiple branches in `exp`, but the `rtol` used in the tests is `1e-8`, not >1, so I'm not sure that's the primary reason for the failure I'm seeing.

### PR DESCRIPTION
**Pull request by sethaxen**
Fixes #595

### CODE REVIEW

File: test/rulesets/LinearAlgebra/matfun.jl [hunk 1]
```diff
@@ -14,6 +14,11 @@
             A = Float64[0 10 0 0; -1 0 0 0; 0 0 0 0; -2 0 0 0]
             test_frule(LinearAlgebra.exp!, A)
         end
+        @testset "imbalanced A with no squaring" begin
+            # https://github.com/JuliaDiff/ChainRules.jl/issues/595
+            A = randn(MersenneTwister(8), 3, 3)
```
Comment (oxinabox) [inline test/rulesets/LinearAlgebra/matfun.jl:19]: Maybe using a literal rather than risk the MersenneTwister changing?
(Like it has done in the past)
```suggestion
            A = [
                -0.007623430669065629 -0.567237096385192  0.4419041897734335;
                 2.090838913114862    -1.254084243281689 -0.04145771190198238;
                 2.3397892123412833   -0.6650489083959324 0.6387266010923911
                ]
```

File: test/rulesets/LinearAlgebra/matfun.jl [hunk 2]
```diff
@@ -48,6 +53,11 @@
             A = Float64[0 10 0 0; -1 0 0 0; 0 0 0 0; -2 0 0 0]
             test_rrule(exp, A; check_inferred=false)
         end
+        @testset "imbalanced A with no squaring" begin
+            # https://github.com/JuliaDiff/ChainRules.jl/issues/595
+            A = randn(MersenneTwister(8), 3, 3)
```
Comment (oxinabox) [inline test/rulesets/LinearAlgebra/matfun.jl:58]: Maybe using a literal rather than risk the MersenneTwister changing?
(Like it has done in the past)
```suggestion
            A = [
                -0.007623430669065629 -0.567237096385192  0.4419041897734335;
                 2.090838913114862    -1.254084243281689 -0.04145771190198238;
                 2.3397892123412833   -0.6650489083959324 0.6387266010923911
                ]
```

**Review by oxinabox — APPROVED** [review]
nice work. merge and tag when happy

**Comment by StevenWhitaker** [comment]
Thanks for working on this @sethaxen. I noticed that there are other random seeds that still fail (I'll post specifics in the #595); do you want to merge this anyway, or wait to resolve the other issues?

**Comment by sethaxen** [comment]
> Thanks for working on this @sethaxen. I noticed that there are other random seeds that still fail (I'll post specifics in the #595); do you want to merge this anyway, or wait to resolve the other issues?

Thanks, @StevenWhitaker! It turns out the remaining seeds failed due to truncation error due to not using all of the intermediates. I fixed that also in this PR and added a test that checks 100 random matrices (I typically found one of the first 10 or so would fail before this fix).

Can you verify that this now works for all of your seeds?

**Comment by StevenWhitaker** [comment]
Everything looks great on my end!

**Comment by StevenWhitaker** [comment]
Out of curiosity, when will this get merged and tagged? @sethaxen

**Comment by sethaxen** [comment]
Thanks for the reminder, I think this is good to go, would be good to get one last review from @oxinabox before merging.

**Comment by StevenWhitaker** [comment]
Bump

**Comment by sethaxen** [comment]
@oxinabox, can you re-review this PR before I merge?

**Review by mcabbott — APPROVED** [review]
I have not worked through the maths here. But it seems to have good tests!
