### PR TITLE
Add complex tests and fix rules for BLAS functions

### LINKED ISSUE #214: Missing tests for BLAS rules
Rules for the following functions are completely untested:
- `BLAS.dot`
- `BLAS.nrm2`
- `BLAS.asum`

Rules for the following functions are not constrained to real inputs but are untested for complex inputs:
- `BLAS.gemv`
- `BLAS.gemm`

### PR DESCRIPTION
**Pull request by sethaxen**
As part of #210, this PR fixes #214 by adding missing complex tests for all rules for `BLAS` functions and fixing the rules where necessary. This should be the last piece of v0.7.0.

This PR uses the utility functions from #216, so it is blocked by that PR. Locally all tests pass.

### CODE REVIEW

File: src/rulesets/LinearAlgebra/blas.jl [hunk 1]
```diff
@@ -37,29 +37,34 @@ end
...
 function frule((_, Δx), ::typeof(BLAS.nrm2), x)
     Ω = BLAS.nrm2(x)
-    return Ω, sum(Δx .* @thunk(x * inv(Ω)))
+    s = ifelse(iszero(Ω), one(Ω), Ω)
+    ∂Ω = if eltype(x) <: Real
+        BLAS.dot(x, Δx) / s
+    else
+        sum(zip(x, Δx)) do (xi, Δxi)
+            return _realconjtimes(xi, Δxi)
+        end / s
```
Comment (willtebbutt) [inline src/rulesets/LinearAlgebra/blas.jl:46]: Something like this is probably a bit cleaner
```suggestion
        sum(y -> _realconjtimes(y...), zip(x, Δx)) / s
```

**Comment by sethaxen** [comment]
Thanks!
