### PR TITLE
Fix corner case for repeat

### LINKED ISSUE #627: Error in `repeat` rule
```julia
julia> using ChainRules: rrule

julia> x = rand(1,2,1);

julia> repeat(x, outer=3)  # this is legal
3×2×1 Array{Float64, 3}:
[:, :, 1] =
 0.691325  0.235793
 0.691325  0.235793
 0.691325  0.235793

julia> rrule(repeat, x, outer=3)  # fails on forward pass
ERROR: ArgumentError: number of outer repetitions (1) cannot be less than number of dimensions of input array (3)
Stacktrace:
 [1] check(arr::Array{Float64, 3}, inner::Tuple{Int64, Int64, Int64}, outer::Int64)
   @ Base._RepeatInnerOuter ./abstractarraymath.jl:337
 [2] repeat(arr::Array{Float64, 3}; inner::Tuple{Int64, Int64, Int64}, outer::Int64)
   @ Base._RepeatInnerOuter ./abstractarraymath.jl:283
 [3] repeat(A::Array{Float64, 3}; inner::Tuple{Int64, Int64, Int64}, outer::Int64)
   @ Base ./abstractarraymath.jl:277
 [4] rrule(::typeof(repeat), xs::Array{Float64, 3}; inner::Tuple{Int64, Int64, Int64}, outer::Int64)
   @ ChainRules ~/.julia/packages/ChainRules/AL6Lg/src/rulesets/Base/array.jl:187
 [5] top-level scope
   @ REPL[8]:1
```
Also seen in Zygote, from which (IIRC) this rule was copied:
```julia
julia> Zygote.gradient(x) do x
         repeat(x, outer=3)[1]
       end
ERROR: ArgumentError: number of outer repetitions (1) cannot be less than number of dimensions of input array (3)
```

### PR DESCRIPTION
**Pull request by mzgubic**
Seems to be the minimal solution to close #627

### CODE REVIEW

File: src/rulesets/Base/array.jl [hunk 1]
```diff
@@ -166,18 +166,19 @@ function frule((_, ẋs), ::typeof(repeat), xs::AbstractArray, cnt...; kw...)
     return repeat(xs, cnt...; kw...), repeat(ẋs, cnt...; kw...)
 end
 
-function rrule(::typeof(repeat), xs::AbstractArray; inner=ntuple(Returns(1), ndims(xs)), outer=ntuple(Returns(1), ndims(xs)))
+function rrule(::typeof(repeat), xs::AbstractArray; inner=nothing, outer=nothing)
```
Comment (mzgubic) [inline src/rulesets/Base/array.jl:169]: this brings it in line with https://github.com/JuliaLang/julia/blob/master/base/abstractarraymath.jl#L392

**Review by mcabbott — APPROVED** [review]
