### PR TITLE
Don't ProjectTo in reverse or circshift

### LINKED ISSUE #518: regression: "no method matching ChainRulesCore.ProjectTo" when calling reverse on a vector of functors
Hi,
I'm experiencing a method error I cannot explain.
When I run the following code with [d360d2e6] ChainRulesCore v1.3.0 I get an error:

```Julia
using Flux

m = [
    Dense(2, 2),
    Dense(2, 2),
]

function f(x)
    sum(
        reverse(m)[1](x)
    )
end

gradient(f, [4., 4.])
```

```
ERROR: LoadError: MethodError: no method matching ChainRulesCore.ProjectTo(::Dense{typeof(identity), Matrix{Float32}, Vector{Float32}})
Closest candidates are:
  ChainRulesCore.ProjectTo(::Tridiagonal{T, V} where V<:AbstractVector{T}) where T<:Number at ~/.julia/packages/ChainRulesCore/Voykb/src/projection.jl:382
  ChainRulesCore.ProjectTo(::Bidiagonal{T, V} where V<:AbstractVector{T}) where T<:Number at ~/.julia/packages/ChainRulesCore/Voykb/src/projection.jl:355
  ChainRulesCore.ProjectTo(::UnitLowerTriangular) at ~/.julia/packages/ChainRulesCore/Voykb/src/projection.jl:336
  ...
```
I do not get this error when I use
[d360d2e6] ChainRulesCore v0.10.13

Could this be related to this?
https://github.com/FluxML/Zygote.jl/pull/1051

Edit:
I tried adding the relevant @adjoint that was removed in the PR linked above:

```Julia
Flux.@adjoint function reverse(x::AbstractArray, args...; kwargs...)
    _reverse(t) = reverse(t, args...; kwargs...)
    _reverse(x), Δ->(_reverse(Δ), map(_->nothing, args)...)
end
```
And it works.

versions:
Julia v1.6.2
[587475ba] Flux v0.12.6

### PR DESCRIPTION
**Pull request by oxinabox**
Closes #518 

ProjectTo in these rearranging linear operators seems not worth it.
It causes problems since they are often used on types that are on representing vector spaces -- and ProjectTo is not fully defined on those.
Which then error.
See #518 for more details.

These are fine if we were given good pullback inputs (i.e. if the functions called after did ensure things were good), we preserve those.

(circshift doesn't work on (any?) structurally spaces matrixes anyway)

### CODE REVIEW

**Review by mzgubic — APPROVED** [review]

File: test/rulesets/Base/array.jl [hunk 1]
```diff
@@ -171,7 +171,9 @@ end
 
         # Structured
         y, pb = rrule(reverse, Diagonal([1,2,3]))
-        @test unthunk(pb(rand(3,3))[2]) isa Diagonal
+        # We only preserve structure in this case if given structured tangent (no ProjectTo)
+        @test unthunk(pb(Diagonal([1.1, 2.1, 3.1]))[2]) isa Diagonal
+        @test unthunk(pb(rand(3, 3))[2]) isa AbstractArray
```
Comment (mcabbott) [inline test/rulesets/Base/array.jl:176]: Instead of just testing the absence of projection, how hard would it be to test something that doesn't want it?  Like `rrule(reverse, [(; x=[1,2]), (; x=[3,4])])`.

The structured arrays that do play well with reverse, and might reasonably show up in the wild, are row vectors:
```
julia> reverse([1,2,3]')
1×3 adjoint(::Vector{Int64}) with eltype Int64:
 3  2  1

julia> reverse([1,2,3]', dims=2)
1×3 adjoint(::Vector{Int64}) with eltype Int64:
 3  2  1
```
Not sure they need testing though, they will just work.

Comment (mcabbott) [reply test/rulesets/Base/array.jl:176]: Oh, too slow! Never mind.
